namespace: k-ndp-v01-ndp-monitor-clickhouse-full-benchmark

storage:
  className: nfs
  data:
    size: 10Gi

rbac:
  serviceAccountName: airflow-multiinstance
  airflowNamespace: k-ndp-v01-ndp-monitor-airflow
