apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pred-service-data
  namespace: airflow
  labels:
    app: pred-service
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  # storageClassName: your-storage-class  # раскомментировать если нужен конкретный класс
